#!/usr/bin/env bash
set -euo pipefail

# Markdown -> PDF 生成スクリプト
#
# Pandoc + XeLaTeX を用いて、日本語 PDF を生成する。
# Markdown テーブルは LaTeX の longtable に変換し、ヘッダー行に背景色を付ける。
#
# 使い方:
#   bash 99_script/md_to_pdf.sh input.md output.pdf
#   bash 99_script/md_to_pdf.sh 01_メインシステム/01_要件定義/index.md
#   bash 99_script/md_to_pdf.sh --out PDF出力/01_メインシステム 01_メインシステム/01_要件定義/index.md
#
# 引数のパターン:
#   - 引数 2 個 (input.md output.pdf): プロンプト指定形式
#   - 引数 1 個 (input.md): PDF出力/ ディレクトリに <basename>.pdf を出力
#   - --out OUT_DIR 指定: OUT_DIR に <basename>.pdf を出力(複数 md 可)
#   - 引数 0 個: エラー(対象ファイル必須)
#
# 環境変数:
#   PDF_FONT_NAME="Hiragino Sans"       本文フォント名
#   PDF_MONO_FONT_NAME="Menlo"          等幅フォント名
#   PDF_TABLE_HEADER_BG="EAF2F8"        テーブルヘッダー背景色
#   PDF_TABLE_HEADER_FG="000000"        テーブルヘッダー文字色

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${REPO_ROOT}/PDF出力"
OUT_FILE=""

FONT_NAME="${PDF_FONT_NAME:-Hiragino Sans}"
MONO_FONT_NAME="${PDF_MONO_FONT_NAME:-Menlo}"
TABLE_HEADER_BG="${PDF_TABLE_HEADER_BG:-EAF2F8}"
TABLE_HEADER_FG="${PDF_TABLE_HEADER_FG:-000000}"

usage() {
  cat <<USAGE
Usage:
  $0 input.md output.pdf
  $0 [--out OUT_DIR] [markdown files...]

Options:
  --out OUT_DIR   PDFの出力先ディレクトリ(省略時: <repo>/PDF出力)
  -h, --help      このヘルプを表示

Examples:
  $0 01_メインシステム/01_要件定義/index.md PDF出力/01_メインシステム/01_要件定義/index.pdf
  $0 --out PDF出力/01_メインシステム/01_要件定義 01_メインシステム/01_要件定義/index.md

依存:
  - pandoc:  brew install pandoc
  - xelatex: brew install --cask basictex (or MacTeX)
USAGE
}

MD_FILES=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      [[ $# -lt 2 ]] && { echo "ERROR: --out の後に出力先ディレクトリを指定してください。" >&2; exit 1; }
      OUT_DIR="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      MD_FILES+=("$1")
      shift
      ;;
  esac
done

# 「input.md output.pdf」形式の判定
if [[ ${#MD_FILES[@]} -eq 2 && "${MD_FILES[1]}" == *.pdf ]]; then
  OUT_FILE="${MD_FILES[1]}"
  MD_FILES=("${MD_FILES[0]}")
fi

# 依存チェック
command -v pandoc >/dev/null 2>&1 || {
  echo "ERROR: pandoc が見つかりません。" >&2
  echo "  brew install pandoc" >&2
  exit 1
}

command -v xelatex >/dev/null 2>&1 || {
  echo "ERROR: xelatex が見つかりません。" >&2
  echo "  brew install --cask basictex" >&2
  echo "  その後: eval \"\$(/usr/libexec/path_helper)\"" >&2
  exit 1
}

if [[ ${#MD_FILES[@]} -eq 0 ]]; then
  echo "ERROR: PDF化するMarkdownファイルが指定されていません。" >&2
  echo "例: $0 input.md output.pdf" >&2
  exit 1
fi

# 出力先準備
if [[ -n "$OUT_FILE" ]]; then
  out_dir_only="$(dirname "$OUT_FILE")"
  mkdir -p "$out_dir_only"
  out_dir_abs="$(cd "$out_dir_only" && pwd)"
  OUT_FILE="${out_dir_abs}/$(basename "$OUT_FILE")"
else
  mkdir -p "$OUT_DIR"
  OUT_DIR="$(cd "$OUT_DIR" && pwd)"
fi

WORK_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

STYLE_TEX="$WORK_DIR/pdf_style.tex"
TABLE_FILTER="$WORK_DIR/full_width_tables.lua"

cat > "$STYLE_TEX" <<EOF
% ---- PDF style generated by md_to_pdf.sh ----
\\usepackage[table]{xcolor}
\\usepackage{array}
\\usepackage{longtable}
\\usepackage{booktabs}
\\usepackage{ragged2e}
\\usepackage{caption}
\\definecolor{tableheaderbg}{HTML}{$TABLE_HEADER_BG}
\\definecolor{tableheaderfg}{HTML}{$TABLE_HEADER_FG}

\\setlength{\\tabcolsep}{3pt}
\\renewcommand{\\arraystretch}{1.25}

\\setlength{\\LTleft}{0pt}
\\setlength{\\LTright}{0pt}

\\AtBeginEnvironment{longtable}{\\small}
\\sloppy
EOF

cat > "$TABLE_FILTER" <<'EOF'
-- full_width_tables.lua
-- Markdown table を LaTeX longtable に変換しヘッダー行に背景色を付ける。

local utils = require 'pandoc.utils'

local function latex_escape(s)
  s = tostring(s or "")
  s = s:gsub("\\", "\\textbackslash{}")
  s = s:gsub("([{}])", "\\%1")
  s = s:gsub("([#$%%&_])", "\\%1")
  s = s:gsub("%^", "\\textasciicircum{}")
  s = s:gsub("~", "\\textasciitilde{}")
  s = s:gsub("<", "\\textless{}")
  s = s:gsub(">", "\\textgreater{}")
  s = s:gsub("|", "\\textbar{}")
  s = s:gsub("\r\n", "\n")
  s = s:gsub("\r", "\n")
  s = s:gsub("\n+", "\\\\ ")
  return s
end

local function stringify_cell(cell)
  if cell == nil then return "" end
  if cell.contents ~= nil then return utils.stringify(cell.contents) end
  return utils.stringify(cell)
end

local function row_cells(row)
  if row == nil then return {} end
  if row.cells ~= nil then return row.cells end
  return row
end

local function collect_head_rows(tbl)
  if tbl.head ~= nil and tbl.head.rows ~= nil then return tbl.head.rows end
  return {}
end

local function collect_body_rows(tbl)
  local rows = {}
  if tbl.bodies ~= nil then
    for _, body in ipairs(tbl.bodies) do
      if body.body ~= nil then
        for _, row in ipairs(body.body) do table.insert(rows, row) end
      elseif body.rows ~= nil then
        for _, row in ipairs(body.rows) do table.insert(rows, row) end
      end
    end
  end
  if #rows == 0 and tbl.rows ~= nil then
    for _, row in ipairs(tbl.rows) do table.insert(rows, row) end
  end
  return rows
end

local function collect_foot_rows(tbl)
  if tbl.foot ~= nil and tbl.foot.rows ~= nil then return tbl.foot.rows end
  return {}
end

local function count_columns(tbl, head_rows, body_rows)
  if tbl.colspecs ~= nil and #tbl.colspecs > 0 then return #tbl.colspecs end
  local max_cols = 0
  for _, rows in ipairs({head_rows, body_rows}) do
    for _, row in ipairs(rows) do
      local cells = row_cells(row)
      if #cells > max_cols then max_cols = #cells end
    end
  end
  return max_cols
end

local function cell_length_for_width(text)
  text = tostring(text or "")
  local bytes = #text
  if bytes < 4 then return 4 end
  if bytes > 90 then return 90 end
  return bytes
end

local function calculate_widths(ncols, head_rows, body_rows)
  local weights = {}
  for i = 1, ncols do weights[i] = 6 end
  local function add_row(row)
    local cells = row_cells(row)
    for i = 1, ncols do
      local text = stringify_cell(cells[i])
      local len = cell_length_for_width(text)
      if len > weights[i] then weights[i] = len end
    end
  end
  for _, row in ipairs(head_rows) do add_row(row) end
  for _, row in ipairs(body_rows) do add_row(row) end
  local total = 0
  for i = 1, ncols do total = total + weights[i] end
  local usable = 0.96
  if ncols >= 4 then usable = 0.92 end
  if ncols >= 6 then usable = 0.88 end
  local widths = {}
  for i = 1, ncols do widths[i] = usable * (weights[i] / total) end
  return widths
end

local function make_colspec(widths)
  local parts = {}
  table.insert(parts, "@{}")
  table.insert(parts, "|")
  for _, w in ipairs(widths) do
    table.insert(parts, string.format(">{\\RaggedRight\\arraybackslash}p{%.4f\\linewidth}|", w))
  end
  table.insert(parts, "@{}")
  return table.concat(parts, "")
end

local function render_cells(cells, ncols, is_header)
  local values = {}
  for i = 1, ncols do
    local text = latex_escape(stringify_cell(cells[i]))
    if is_header then text = "\\textcolor{tableheaderfg}{\\textbf{" .. text .. "}}" end
    table.insert(values, text)
  end
  return table.concat(values, " & ") .. " \\\\"
end

local function render_rows(rows, ncols, is_header)
  local out = {}
  for _, row in ipairs(rows) do
    local cells = row_cells(row)
    if is_header then table.insert(out, "\\rowcolor{tableheaderbg}") end
    table.insert(out, render_cells(cells, ncols, is_header))
    table.insert(out, "\\hline")
  end
  return table.concat(out, "\n")
end

local function caption_text(tbl)
  if tbl.caption == nil then return "" end
  if tbl.caption.long ~= nil then
    local s = utils.stringify(tbl.caption.long)
    if s ~= nil and s ~= "" then return latex_escape(s) end
  end
  local s = utils.stringify(tbl.caption)
  return latex_escape(s or "")
end

function Table(tbl)
  if not FORMAT:match("latex") then return tbl end
  local head_rows = collect_head_rows(tbl)
  local body_rows = collect_body_rows(tbl)
  local foot_rows = collect_foot_rows(tbl)
  local ncols = count_columns(tbl, head_rows, body_rows)
  if ncols == 0 then return tbl end
  local widths = calculate_widths(ncols, head_rows, body_rows)
  local colspec = make_colspec(widths)
  local out = {}
  table.insert(out, "\\begin{longtable}{" .. colspec .. "}")
  table.insert(out, "\\hline")
  local cap = caption_text(tbl)
  if cap ~= "" then
    table.insert(out, "\\caption{" .. cap .. "}\\\\")
    table.insert(out, "\\hline")
  end
  if #head_rows > 0 then
    table.insert(out, render_rows(head_rows, ncols, true))
    table.insert(out, "\\endfirsthead")
    table.insert(out, "\\hline")
    table.insert(out, render_rows(head_rows, ncols, true))
    table.insert(out, "\\endhead")
  end
  if #body_rows > 0 then
    table.insert(out, render_rows(body_rows, ncols, false))
  end
  if #foot_rows > 0 then
    table.insert(out, render_rows(foot_rows, ncols, false))
  end
  table.insert(out, "\\end{longtable}")
  return pandoc.RawBlock("latex", table.concat(out, "\n"))
end
EOF

for md in "${MD_FILES[@]}"; do
  if [[ ! -f "$md" ]]; then
    echo "ERROR: ファイルが見つかりません: $md" >&2
    exit 1
  fi

  if [[ -n "$OUT_FILE" ]]; then
    pdf="$OUT_FILE"
  else
    base="$(basename "$md" .md)"
    pdf="$OUT_DIR/${base}.pdf"
  fi

  echo "Creating PDF: $pdf"
  echo "  main font: $FONT_NAME"
  echo "  mono font: $MONO_FONT_NAME"
  echo "  table header bg: #$TABLE_HEADER_BG"

  pandoc "$md" \
    --from=gfm \
    --pdf-engine=xelatex \
    --output="$pdf" \
    --toc \
    --toc-depth=3 \
    --number-sections \
    --lua-filter="$TABLE_FILTER" \
    --include-in-header="$STYLE_TEX" \
    --resource-path="$(dirname "$md")" \
    -V papersize=a4 \
    -V geometry:margin=18mm \
    -V fontsize=10pt \
    -V mainfont="$FONT_NAME" \
    -V CJKmainfont="$FONT_NAME" \
    -V monofont="$MONO_FONT_NAME" \
    -V colorlinks=true \
    -V linkcolor=blue \
    -V urlcolor=blue

done

if [[ -n "$OUT_FILE" ]]; then
  echo "Done. Output: $OUT_FILE"
else
  echo "Done. Output directory: $OUT_DIR"
fi
