#!/usr/bin/env bash
set -euo pipefail

# Markdown -> PDF 生成スクリプト v4
#
# v3で発生した `Misplaced \noalign` を修正した版です。
# 変更点:
# - 結合PDFは作成しない
# - MarkdownテーブルをLaTeXのlongtableとして安全に出力する
# - テーブルを横幅いっぱいに表示しやすくする
# - テーブルのヘッダー行に背景色を付ける
# - 日本語PDF向けに XeLaTeX を使用する
#
# 使い方:
#   chmod 755 create_pdf_v4.sh
#   ./create_pdf_v4.sh requirements.md specification.md
#
# 出力先を指定:
#   ./create_pdf_v4.sh --out ./pdf_output requirements.md specification.md
#
# フォントや色を変える:
#   PDF_FONT_NAME="Noto Sans CJK JP" PDF_MONO_FONT_NAME="Noto Sans Mono CJK JP" PDF_TABLE_HEADER_BG="D9EAF7" ./create_pdf_v4.sh requirements.md specification.md

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$SCRIPT_DIR/pdf_output"

# Mac標準フォントを初期値にする。
# Noto Sans CJK JPを使いたい場合は、環境変数 PDF_FONT_NAME で上書きしてください。
FONT_NAME="${PDF_FONT_NAME:-Hiragino Sans}"
MONO_FONT_NAME="${PDF_MONO_FONT_NAME:-Menlo}"

# テーブルヘッダー背景色。HTMLカラーコードの # は付けない。
TABLE_HEADER_BG="${PDF_TABLE_HEADER_BG:-EAF2F8}"
TABLE_HEADER_FG="${PDF_TABLE_HEADER_FG:-000000}"

usage() {
  cat <<USAGE
Usage: $0 [--out OUT_DIR] [markdown files...]

Options:
  --out OUT_DIR   PDFの出力先ディレクトリを指定します。省略時: ./pdf_output
  -h, --help      このヘルプを表示します。

Examples:
  $0 requirements.md specification.md
  $0 --out ./dist requirements.md specification.md

Environment:
  PDF_FONT_NAME="Hiragino Sans"       本文フォント名を変更できます。
  PDF_MONO_FONT_NAME="Menlo"          等幅フォント名を変更できます。
  PDF_TABLE_HEADER_BG="EAF2F8"        テーブルヘッダー背景色を変更できます。
  PDF_TABLE_HEADER_FG="000000"        テーブルヘッダー文字色を変更できます。
USAGE
}

MD_FILES=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --out の後に出力先ディレクトリを指定してください。" >&2
        exit 1
      fi
      OUT_DIR="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      MD_FILES+=("$1")
      shift
      ;;
  esac
done

command -v pandoc >/dev/null 2>&1 || {
  echo "ERROR: pandoc が見つかりません。" >&2
  echo "例: arch -arm64 brew install pandoc" >&2
  exit 1
}

command -v xelatex >/dev/null 2>&1 || {
  echo "ERROR: xelatex が見つかりません。" >&2
  echo "例: arch -arm64 brew install --cask basictex" >&2
  echo "その後: eval \"\$(/usr/libexec/path_helper)\"" >&2
  exit 1
}

if [[ ${#MD_FILES[@]} -eq 0 ]]; then
  for f in \
    "$SCRIPT_DIR/faq_ai_widget_saas_requirements_v1_6_revised.md" \
    "$SCRIPT_DIR/faq_ai_widget_saas_specification_v1_6_revised.md" \
    "$SCRIPT_DIR/requirements.md" \
    "$SCRIPT_DIR/specification.md" \
    "$SCRIPT_DIR/requirements(3).md" \
    "$SCRIPT_DIR/specification(2).md"; do
    [[ -f "$f" ]] && MD_FILES+=("$f")
  done
fi

if [[ ${#MD_FILES[@]} -eq 0 ]]; then
  echo "ERROR: PDF化するMarkdownファイルが見つかりません。" >&2
  echo "例: $0 requirements.md specification.md" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

WORK_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

STYLE_TEX="$WORK_DIR/pdf_style.tex"
TABLE_FILTER="$WORK_DIR/full_width_tables.lua"

cat > "$STYLE_TEX" <<EOF
% ---- PDF style generated by create_pdf_v4.sh ----
\\usepackage[table]{xcolor}
\\usepackage{array}
\\usepackage{longtable}
\\usepackage{booktabs}
\\usepackage{ragged2e}
\\usepackage{caption}
\\definecolor{tableheaderbg}{HTML}{$TABLE_HEADER_BG}
\\definecolor{tableheaderfg}{HTML}{$TABLE_HEADER_FG}

% 表の余白と行間
\\setlength{\\tabcolsep}{3pt}
\\renewcommand{\\arraystretch}{1.25}

% longtableを紙面の左端から右端まで使いやすくする
\\setlength{\\LTleft}{0pt}
\\setlength{\\LTright}{0pt}

% 表が詰まりすぎないようにする
\\AtBeginEnvironment{longtable}{\\small}
\\sloppy
EOF

cat > "$TABLE_FILTER" <<'EOF'
-- full_width_tables.lua
--
-- PandocのTableをRaw LaTeXのlongtableへ変換する。
-- v3のようにセル内へ \rowcolor を入れず、行の直前に置くため
-- `Misplaced \noalign` を回避できる。

local utils = require 'pandoc.utils'

local function latex_escape(s)
  s = tostring(s or "")
  s = s:gsub("\\", "\\textbackslash{}")
  s = s:gsub("([{}])", "\\%1")
  s = s:gsub("([#$%%&_])", "\\%1")
  s = s:gsub("%^", "\\textasciicircum{}")
  s = s:gsub("~", "\\textasciitilde{}")
  s = s:gsub("<", "\\textless{}")
  s = s:gsub(">", "\\textgreater{}")
  s = s:gsub("|", "\\textbar{}")
  s = s:gsub("\r\n", "\n")
  s = s:gsub("\r", "\n")
  s = s:gsub("\n+", "\\\\ ")
  return s
end

local function stringify_cell(cell)
  if cell == nil then
    return ""
  end

  if cell.contents ~= nil then
    return utils.stringify(cell.contents)
  end

  return utils.stringify(cell)
end

local function row_cells(row)
  if row == nil then
    return {}
  end

  if row.cells ~= nil then
    return row.cells
  end

  return row
end

local function collect_head_rows(tbl)
  if tbl.head ~= nil and tbl.head.rows ~= nil then
    return tbl.head.rows
  end
  return {}
end

local function collect_body_rows(tbl)
  local rows = {}

  if tbl.bodies ~= nil then
    for _, body in ipairs(tbl.bodies) do
      if body.body ~= nil then
        for _, row in ipairs(body.body) do
          table.insert(rows, row)
        end
      elseif body.rows ~= nil then
        for _, row in ipairs(body.rows) do
          table.insert(rows, row)
        end
      end
    end
  end

  -- 古いPandoc向けの保険
  if #rows == 0 and tbl.rows ~= nil then
    for _, row in ipairs(tbl.rows) do
      table.insert(rows, row)
    end
  end

  return rows
end

local function collect_foot_rows(tbl)
  if tbl.foot ~= nil and tbl.foot.rows ~= nil then
    return tbl.foot.rows
  end
  return {}
end

local function count_columns(tbl, head_rows, body_rows)
  if tbl.colspecs ~= nil and #tbl.colspecs > 0 then
    return #tbl.colspecs
  end

  local max_cols = 0
  for _, rows in ipairs({head_rows, body_rows}) do
    for _, row in ipairs(rows) do
      local cells = row_cells(row)
      if #cells > max_cols then
        max_cols = #cells
      end
    end
  end

  return max_cols
end

local function cell_length_for_width(text)
  text = tostring(text or "")
  -- 日本語はUTF-8でバイト数が大きくなるため、ざっくり補正する。
  local bytes = #text
  if bytes < 4 then
    return 4
  end
  if bytes > 90 then
    return 90
  end
  return bytes
end

local function calculate_widths(ncols, head_rows, body_rows)
  local weights = {}
  for i = 1, ncols do
    weights[i] = 6
  end

  local function add_row(row)
    local cells = row_cells(row)
    for i = 1, ncols do
      local text = stringify_cell(cells[i])
      local len = cell_length_for_width(text)
      if len > weights[i] then
        weights[i] = len
      end
    end
  end

  for _, row in ipairs(head_rows) do
    add_row(row)
  end
  for _, row in ipairs(body_rows) do
    add_row(row)
  end

  local total = 0
  for i = 1, ncols do
    total = total + weights[i]
  end

  -- 罫線・セル余白ぶんを少し引いて、見た目として本文幅いっぱいに近づける。
  local usable = 0.96
  if ncols >= 4 then
    usable = 0.92
  end
  if ncols >= 6 then
    usable = 0.88
  end

  local widths = {}
  for i = 1, ncols do
    widths[i] = usable * (weights[i] / total)
  end

  return widths
end

local function make_colspec(widths)
  local parts = {}
  table.insert(parts, "@{}")
  table.insert(parts, "|")
  for _, w in ipairs(widths) do
    table.insert(parts, string.format(">{\\RaggedRight\\arraybackslash}p{%.4f\\linewidth}|", w))
  end
  table.insert(parts, "@{}")
  return table.concat(parts, "")
end

local function render_cells(cells, ncols, is_header)
  local values = {}

  for i = 1, ncols do
    local text = latex_escape(stringify_cell(cells[i]))
    if is_header then
      text = "\\textcolor{tableheaderfg}{\\textbf{" .. text .. "}}"
    end
    table.insert(values, text)
  end

  return table.concat(values, " & ") .. " \\\\"
end

local function render_rows(rows, ncols, is_header)
  local out = {}

  for _, row in ipairs(rows) do
    local cells = row_cells(row)
    if is_header then
      table.insert(out, "\\rowcolor{tableheaderbg}")
    end
    table.insert(out, render_cells(cells, ncols, is_header))
    table.insert(out, "\\hline")
  end

  return table.concat(out, "\n")
end

local function caption_text(tbl)
  if tbl.caption == nil then
    return ""
  end

  -- Pandoc 3系: caption.long / caption.short
  if tbl.caption.long ~= nil then
    local s = utils.stringify(tbl.caption.long)
    if s ~= nil and s ~= "" then
      return latex_escape(s)
    end
  end

  -- 念のため
  local s = utils.stringify(tbl.caption)
  return latex_escape(s or "")
end

function Table(tbl)
  if not FORMAT:match("latex") then
    return tbl
  end

  local head_rows = collect_head_rows(tbl)
  local body_rows = collect_body_rows(tbl)
  local foot_rows = collect_foot_rows(tbl)
  local ncols = count_columns(tbl, head_rows, body_rows)

  if ncols == 0 then
    return tbl
  end

  local widths = calculate_widths(ncols, head_rows, body_rows)
  local colspec = make_colspec(widths)

  local out = {}
  table.insert(out, "\\begin{longtable}{" .. colspec .. "}")
  table.insert(out, "\\hline")

  local cap = caption_text(tbl)
  if cap ~= "" then
    table.insert(out, "\\caption{" .. cap .. "}\\\\")
    table.insert(out, "\\hline")
  end

  if #head_rows > 0 then
    table.insert(out, render_rows(head_rows, ncols, true))
    table.insert(out, "\\endfirsthead")
    table.insert(out, "\\hline")
    table.insert(out, render_rows(head_rows, ncols, true))
    table.insert(out, "\\endhead")
  end

  if #body_rows > 0 then
    table.insert(out, render_rows(body_rows, ncols, false))
  end

  if #foot_rows > 0 then
    table.insert(out, render_rows(foot_rows, ncols, false))
  end

  table.insert(out, "\\end{longtable}")

  return pandoc.RawBlock("latex", table.concat(out, "\n"))
end
EOF

for md in "${MD_FILES[@]}"; do
  if [[ ! -f "$md" ]]; then
    echo "ERROR: ファイルが見つかりません: $md" >&2
    exit 1
  fi

  base="$(basename "$md" .md)"
  pdf="$OUT_DIR/${base}.pdf"

  echo "Creating PDF: $pdf"
  echo "  main font: $FONT_NAME"
  echo "  mono font: $MONO_FONT_NAME"
  echo "  table header bg: #$TABLE_HEADER_BG"

  pandoc "$md" \
    --from=gfm \
    --pdf-engine=xelatex \
    --output="$pdf" \
    --toc \
    --toc-depth=3 \
    --number-sections \
    --lua-filter="$TABLE_FILTER" \
    --include-in-header="$STYLE_TEX" \
    --resource-path="$(dirname "$md")" \
    -V papersize=a4 \
    -V geometry:margin=18mm \
    -V fontsize=10pt \
    -V mainfont="$FONT_NAME" \
    -V CJKmainfont="$FONT_NAME" \
    -V monofont="$MONO_FONT_NAME" \
    -V colorlinks=true \
    -V linkcolor=blue \
    -V urlcolor=blue

done

echo "Done. Output directory: $OUT_DIR"
